[project]
name = "chainofcode"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sean Murphy", email = "seandata8@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "holidays>=0.105",
    "ollama>=0.6.3",
    "python-dateutil>=2.9.0.post0",
]

[project.scripts]
chainofcode = "chainofcode:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
